# Generated by Django 2.2 on 2019-09-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('did', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuer',
            name='id',
        ),
        migrations.AlterField(
            model_name='issuer',
            name='did',
            field=models.CharField(max_length=48, primary_key=True, serialize=False),
        ),
    ]
