# Generated by Django 2.2 on 2019-09-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('did', '0002_auto_20190914_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField()),
                ('expired_time', models.DateTimeField()),
                ('applicant_did', models.CharField(max_length=48)),
                ('type', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('battery_capacity', models.CharField(max_length=100)),
                ('issuer_did', models.CharField(max_length=200)),
                ('sig', models.BinaryField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Claim',
        ),
    ]
